name: Pre-Commit

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  preCommit:
    name: pre-commit
    runs-on: eks
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install pre-commit dependencies
        run: |
          pip install pre-commit
          curl -L "$(curl -s https://api.github.com/repos/terraform-linters/tflint/releases/latest | grep -o -E "https://.+?_linux_amd64.zip")" > tflint.zip && unzip tflint.zip && rm tflint.zip && sudo mv tflint /usr/bin/
          curl -L https://raw.githubusercontent.com/warrensbox/terraform-switcher/release/install.sh | sudo bash &&\
            tfswitch
      - name: Execute pre-commit
        run: pre-commit run --color=always --show-diff-on-failure --all-files
